ARG NGINX_IMAGE=nginx:1.29.8-alpine3.23-slim@sha256:c9366b8c560169b101ca0e5422ed063b20779e6454c2326b9c9704225c9b0c08

FROM ${NGINX_IMAGE}
RUN apk upgrade --no-cache && rm -f /etc/nginx/conf.d/default.conf
COPY infra/edge/nginx-edge.conf /etc/nginx/conf.d/edge.conf
