server_name: swarmcast-segment-bus
port: 4222
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
  max_memory_store: 256MB
  max_file_store: 2GB
}

authorization {
  timeout: 2
  users: [
    {
      user: $NATS_INGEST_USER
      password: $NATS_INGEST_PASSWORD
      permissions: {
        publish: [
          "swarmcast.segment.>",
          "$JS.API.INFO",
          "$JS.API.STREAM.INFO.SWARMCAST_SEGMENTS",
          "$JS.API.STREAM.CREATE.SWARMCAST_SEGMENTS",
          "$JS.API.STREAM.UPDATE.SWARMCAST_SEGMENTS"
        ]
        subscribe: ["_INBOX.>"]
      }
    },
    {
      user: $NATS_TRACKER_USER
      password: $NATS_TRACKER_PASSWORD
      permissions: {
        publish: [
          "$JS.API.INFO",
          "$JS.API.STREAM.INFO.SWARMCAST_SEGMENTS",
          "$JS.API.STREAM.MSG.GET.SWARMCAST_SEGMENTS"
        ]
        subscribe: ["swarmcast.segment.>", "_INBOX.>"]
      }
    }
  ]
}
